Add new build-summary job

diff --git a/.github/workflows/build-check.yml b/.github/workflows/build-check.yml
--- a/.github/workflows/build-check.yml
+++ b/.github/workflows/build-check.yml
@@ -33,5 +33,21 @@ jobs:
         with:
           cache: go
 
-      - name: Build
+      - name: Build Collector with Contrib Modules
         run: make -C contrib ${{ matrix.target }} COLLECTOR_PATH=../collector
+
+  build-summary:
+    if: always()
+    needs: [build-collector]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check build results
+        run: |
+          if [[ "${{ needs.build-collector.result }}" == "success" ]]; then
+            echo "All builds succeeded"
+          elif [[ "${{ needs.build-collector.result }}" == "skipped" ]]; then
+            echo "Build skipped"
+          else
+            echo "Builds failed"
+            exit 1
+          fi
